### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by thecodeduchess** [Eukelade/bwa-u3-jammming-prj#2]
**Grade: Meets Expectations**

**Summary:** This was a great implementation of the Jammming project. First, I test your project by downloading it and viewing it in my own browser. Next, I go step by step with your page against the requirements.  It matches to my specs exactly. After nitpicking through it, I did not find anything that requires a re-do.

The code was easily readable and met the required styling, class and ID naming.
I am able to connect to Spotify, search and save playlists. 

You are allowed to change the background, color scheme or fonts to your liking so don't be afraid to play around with that. You can make it your own. 

I hope you are enjoying your learning experience. You are certainly ready to move on to the next step. Good luck with your feature request.

**Comment by Eukelade** [comment]
I am really happy and thrilled that my code meets expectations as this is basically my first programming effort in quite a while and completely new programming language. 

I do like my learning experience with your courses and look forward to learn new things.
